# Name of the GitHub Actions workflow (shown in the Actions tab)
name: Java Build with Gradle

# Trigger this workflow on every push to any branch
on:
  push:

jobs:
  build:
    # Run this job on the latest Ubuntu Linux runner hosted by GitHub
    runs-on: ubuntu-latest

    # Define permission scope for this job (read access to repo contents)
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the latest code from the GitHub repository
      - uses: actions/checkout@v4
        # Ensures all code and build scripts are available for the workflow

      # Step 2: Set up Java 21 using Temurin distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'            # Specify the Java version
          distribution: 'temurin'       # Use Temurin (Eclipse Adoptium) JDK
          cache: 'gradle'               # Enable dependency caching for Gradle

      # Step 3: Setup Gradle wrapper environment (includes caching)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        # This automatically detects and caches Gradle dependencies
        # It also ensures consistent wrapper usage

      # Step 4: Ensure Gradle wrapper script is executable on Unix-based runners
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        # Especially required on Ubuntu or Mac OS runners

      # Step 5: Compile code and run tests with coverage enabled
      - name: Build and Run Tests with JaCoCo Coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon --stacktrace
        # - `clean`: Clean previous build output
        # - `test`: Runs all unit tests
        # - `jacocoTestReport`: Generates code coverage reports (HTML, XML)

      # Step 6: Upload JaCoCo HTML coverage report as an artifact
      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html
        # This makes the HTML coverage report downloadable from the Actions tab
